# Generated by Django 5.0.4 on 2024-05-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('water_level', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('kp', models.FloatField(default=0)),
                ('ki', models.FloatField(default=0)),
                ('kd', models.FloatField(default=0)),
                ('output', models.FloatField(default=0)),
                ('pump_on', models.FloatField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.run')),
            ],
        ),
    ]
