# Generated by Django 5.0.4 on 2024-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
