# Generated by Django 5.0.4 on 2024-05-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_rundata_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundata',
            name='kd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rundata',
            name='ki',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rundata',
            name='kp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rundata',
            name='output',
            field=models.FloatField(default=0),
        ),
    ]
